[2024-10-16T09:38:25.930+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: exchange_rate_usd_rus_dag.create_table_task scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-10-16T09:38:25.942+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: exchange_rate_usd_rus_dag.create_table_task scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-10-16T09:38:25.942+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-10-16T09:38:25.945+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2024-10-16T09:38:25.947+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-10-16T09:38:25.962+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): create_table_task> on 2024-07-23 00:00:00+00:00
[2024-10-16T09:38:25.967+0000] {standard_task_runner.py:55} INFO - Started process 3899 to run task
[2024-10-16T09:38:25.971+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_usd_rus_dag', 'create_table_task', 'scheduled__2024-07-23T00:00:00+00:00', '--job-id', '296', '--raw', '--subdir', 'DAGS_FOLDER/RUS_DAG.py', '--cfg-path', '/tmp/tmpk9ez2a_0']
[2024-10-16T09:38:25.972+0000] {standard_task_runner.py:83} INFO - Job 296: Subtask create_table_task
[2024-10-16T09:38:26.045+0000] {task_command.py:389} INFO - Running <TaskInstance: exchange_rate_usd_rus_dag.create_table_task scheduled__2024-07-23T00:00:00+00:00 [running]> on host 63ee4fa64e74
[2024-10-16T09:38:26.079+0000] {abstractoperator.py:596} ERROR - Exception rendering Jinja template for task 'create_table_task', field 'sql'. Template: 'sql/create_table.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 640, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2024-10-16T09:38:26.081+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1378, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1497, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2119, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1196, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 640, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/create_table.sql
[2024-10-16T09:38:26.090+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=exchange_rate_usd_rus_dag, task_id=create_table_task, execution_date=20240723T000000, start_date=20241016T093825, end_date=20241016T093826
[2024-10-16T09:38:26.102+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 296 for task create_table_task (sql/create_table.sql; 3899)
[2024-10-16T09:38:26.150+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-10-16T09:38:26.178+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-16T09:49:07.186+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: exchange_rate_usd_rus_dag.create_table_task scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-10-16T09:49:07.203+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: exchange_rate_usd_rus_dag.create_table_task scheduled__2024-07-23T00:00:00+00:00 [queued]>
[2024-10-16T09:49:07.204+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-10-16T09:49:07.205+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2024-10-16T09:49:07.206+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-10-16T09:49:07.233+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): create_table_task> on 2024-07-23 00:00:00+00:00
[2024-10-16T09:49:07.241+0000] {standard_task_runner.py:55} INFO - Started process 6651 to run task
[2024-10-16T09:49:07.249+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_usd_rus_dag', 'create_table_task', 'scheduled__2024-07-23T00:00:00+00:00', '--job-id', '1073', '--raw', '--subdir', 'DAGS_FOLDER/RUS_DAG.py', '--cfg-path', '/tmp/tmpeoc6lnyj']
[2024-10-16T09:49:07.253+0000] {standard_task_runner.py:83} INFO - Job 1073: Subtask create_table_task
[2024-10-16T09:49:07.407+0000] {task_command.py:389} INFO - Running <TaskInstance: exchange_rate_usd_rus_dag.create_table_task scheduled__2024-07-23T00:00:00+00:00 [running]> on host 63ee4fa64e74
[2024-10-16T09:49:07.588+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=exchange_rate_usd_rus_dag
AIRFLOW_CTX_TASK_ID=create_table_task
AIRFLOW_CTX_EXECUTION_DATE=2024-07-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-23T00:00:00+00:00
[2024-10-16T09:49:07.592+0000] {sql.py:253} INFO - Executing: CREATE TABLE IF NOT EXISTS currency_exchange_rates (
    base VARCHAR(3) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    rate NUMERIC(12, 3) NOT NULL,
    date DATE NOT NULL,
    UNIQUE (base, currency, date)
);
[2024-10-16T09:49:07.621+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2024-10-16T09:49:08.072+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2024-10-16T09:49:08.088+0000] {sql.py:364} INFO - Running statement: CREATE TABLE IF NOT EXISTS currency_exchange_rates (
    base VARCHAR(3) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    rate NUMERIC(12, 3) NOT NULL,
    date DATE NOT NULL,
    UNIQUE (base, currency, date)
);, parameters: None
[2024-10-16T09:49:08.115+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=exchange_rate_usd_rus_dag, task_id=create_table_task, execution_date=20240723T000000, start_date=20241016T094907, end_date=20241016T094908
[2024-10-16T09:49:08.175+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-10-16T09:49:08.264+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
